services:
  qbittorrent:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/qbittorrent:latest
    volumes:
      - "{{ MEDIA__DOWNLOAD_DIR}}/:/downloads"
      - /srv/storage/remote/raid10/qbittorrent__incomplete/:/downloading
      - /srv/storage/local/main/qbittorrent/:/config
    environment:
      PGID: "{{ MEDIA__GROUP }}"
      WEBUI_PORT: 8080
      VIRTUAL_HOST: qbittorrent.gabbro
      VIRTUAL_PORT: 8080
    ports:
      - 6881:6881
      - 6881:6881/udp
