services:
  qbittorrent:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/qbittorrent:latest
    volumes:
      - "{{ MEDIA__DOWNLOAD_DIR}}/:/downloads"
      - /mnt/celery/gabbro/qbittorrent/incomplete/:/downloading
      - /mnt/celery/gabbro/qbittorrent/config/:/config
    environment:
      WEBUI_PORT: 8080
      VIRTUAL_HOST: qbittorrent.gabbro
      VIRTUAL_PORT: 8080
    ports:
      - 6881:6881
      - 6881:6881/udp
