services:
  qbittorrent:
    deploy:
      resources:
        limits:
          memory: 2gb
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:ffa4e82aa55e3bd3d2d99151f235fcd41b976303c4d4029940363452a59a3833
    x-tl: +!
    volumes:
      - "{{ MEDIA__DOWNLOAD_DIR}}/:/downloads"
      - /mnt/celery/gabbro/qbittorrent/incomplete/:/downloading
      - /mnt/celery/gabbro/qbittorrent/config/:/config
    environment:
      WEBUI_PORT: 8080
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "qbittorrent.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    ports:
      - 6881:6881
      - 6881:6881/udp
