services:
  qbittorrent:
    deploy:
      resources:
        limits:
          memory: 2gb
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:ca6325989299ff807ab94c9505c138b6cadfe8a77c4ef14c5690094cbbe40d7d
    x-tl: +!
    volumes:
      - "{{ MEDIA__DOWNLOAD_DIR}}/:/downloads"
      - /mnt/celery/gabbro/qbittorrent/incomplete/:/downloading
      - /mnt/celery/gabbro/qbittorrent/config/:/config
    environment:
      WEBUI_PORT: 8080
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "qbittorrent.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    ports:
      - 6881:6881
      - 6881:6881/udp
