services:
  qbittorrent:
    deploy:
      resources:
        limits:
          memory: 2gb
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:50f490770308d0351e12618422e74e0613721b080f5db0bf840cf66a7281eea8
    x-tl: +!
    volumes:
      - "{{ MEDIA__DOWNLOAD_DIR}}/:/downloads"
      - /mnt/celery/gabbro/qbittorrent/incomplete/:/downloading
      - /mnt/celery/gabbro/qbittorrent/config/:/config
    environment:
      WEBUI_PORT: 8080
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "qbittorrent.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    ports:
      - 6881:6881
      - 6881:6881/udp
