services:
  qbittorrent:
    deploy:
      resources:
        limits:
          memory: 2gb
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:804854c50e27e093425eeb252af15e5b587670afb689c8773e4d8ade8ce456b7
    x-tl: +!
    volumes:
      - "{{ MEDIA__DOWNLOAD_DIR}}/:/downloads"
      - /mnt/celery/gabbro/qbittorrent/incomplete/:/downloading
      - /mnt/celery/gabbro/qbittorrent/config/:/config
    environment:
      WEBUI_PORT: 8080
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "qbittorrent.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    ports:
      - 6881:6881
      - 6881:6881/udp
