services:
  qbittorrent:
    deploy:
      resources:
        limits:
          memory: 2gb
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:90a82ca3ad221a8df88f245aec649f0c10b83109dfdacec14fb33e345e605560
    x-tl: +!
    volumes:
      - "{{ MEDIA__DOWNLOAD_DIR}}/:/downloads"
      - /mnt/celery/gabbro/qbittorrent/incomplete/:/downloading
      - /mnt/celery/gabbro/qbittorrent/config/:/config
    environment:
      WEBUI_PORT: 8080
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "qbittorrent.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    ports:
      - 6881:6881
      - 6881:6881/udp
