services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      WEBUI_PORT: 8080
      VIRTUAL_HOST: qbittorrent.gabbro
      VIRTUAL_PORT: 8080
    ports:
      - 6881:6881
      - 6881:6881/udp