services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest@sha256:ae0a555aa5cebfc9d510c8a7b439e210db2556e36757d10f2989b850a5e63b81
    x-tl: +!
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      SERVERURL: "{{ COM_GABBRO_WIREGUARD__SERVER_URL }}"
      SERVERPORT: 51820
      PEERS: 1
    volumes:
      - /mnt/celery/gabbro/wireguard/:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp

