services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest@sha256:ee2db24277b43ec4e7529e93967dc3cea00a02bf81b749c680b2b102a6e4aa5b
    x-tl: +!
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      SERVERURL: "{{ COM_GABBRO_WIREGUARD__SERVER_URL }}"
      SERVERPORT: 51820
      PEERS: 1
    volumes:
      - /mnt/celery/gabbro/wireguard/:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp

