services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest@sha256:0dfaeb571eb3cf438d5c34508d49d7bf29df938d408a92da0448a9e8328a7819
    x-tl: +!
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      SERVERURL: "{{ COM_GABBRO_WIREGUARD__SERVER_URL }}"
      SERVERPORT: 51820
      PEERS: 1
    volumes:
      - /mnt/celery/gabbro/wireguard/:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp

