services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest@sha256:84c9fef8070216cf2c834e90af62e4a45226aa64e9fb0a3d3b9d13bceaaf8f34
    x-tl: +!
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      SERVERURL: "{{ COM_GABBRO_WIREGUARD__SERVER_URL }}"
      SERVERPORT: 51820
      PEERS: 1
    volumes:
      - /mnt/celery/gabbro/wireguard/:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
