services:
  firefly_iii:
    networks:
      - nginx
      - firefly_iii
    image: docker.io/fireflyiii/core:latest@sha256:ac842bc5b7a66f40f9680b27e03f9155907741ce8940bb3a3ceffa99f43b200a
    x-tl: "+!"
    volumes:
      - /mnt/celery/gabbro/firefly_iii/upload/:/var/www/html/storage/upload
    env_file:
      - ./firefly_iii/firefly_iii.env
    environment:
      VIRTUAL_HOST: firefly-iii.gabbro
      VIRTUAL_PORT: 8080
    depends_on:
      - firefly_iii_db
  firefly_iii_db:
    networks:
      - firefly_iii
    image: mariadb
    x-tl: x
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ COM_GABBRO_FIREFLY_III__DB__USERNAME }}"
      MYSQL_PASSWORD: "{{ COM_GABBRO_FIREFLY_III__DB__PASSWORD }}"
      MYSQL_DATABASE: firefly
    volumes:
      - /mnt/celery/gabbro/firefly_iii/db/:/var/lib/mysql
  firefly_iii_importer:
    networks:
      - firefly_iii
      - nginx
    image: docker.io/fireflyiii/data-importer:latest@sha256:40e10f996a7bf72285dd6475c49424a02255fb02437904fe2ee6c44bc07e1bfc
    x-tl: "+!"
    depends_on:
      - firefly_iii
    environment:
      VIRTUAL_HOST: firefly-iii-di.gabbro
      VIRTUAL_PORT: 8080
      FIREFLY_III_URL: 'http://firefly_iii:8080'
      FIREFLY_III_ACCESS_TOKEN: '{{ COM_GABBRO_FIREFLY_III__ACCESS_TOKEN }}'
  firefly_iii_pp_node_red:
    networks:
      - firefly_iii
      - nginx
    image: docker.io/nodered/node-red:latest@sha256:7a3e18f29578feb271bb8daab4379e4ebd355b87ea64b699ce74e6ff49d907aa
    x-tl: "+!"
    environment:
      VIRTUAL_HOST: firefly-iii-nr.gabbro
      VIRTUAL_PORT: 1880
    volumes:
      - ./firefly_iii/settings.js:/data/settings.js
      - firefly-iii-node-red-data:/data
  firefly_iii_pp:
    networks:
      - firefly_iii
      - nginx
    image: docker.io/haumea/fireflyiii-pp:latest@sha256:225731fec9cc7ef7f9101cd0725e62386e294ad2d3dac0208fcdc524ea817d3d
    x-tl: "+!"
    environment:
      VIRTUAL_HOST: firefly-iii-pp.gabbro
      VIRTUAL_PORT: 80
      DOTNET_KeyValueStoreSettings__Stores__assetAccounts__Path: assetAccounts.json
      DOTNET_KeyValueStoreSettings__Stores__assetAccounts__DefaultValueValue: "{\"attributes\":{},\"add_tags\":[]}"
      DOTNET_KeyValueStoreSettings__Stores__expenseAccounts__Path: expenseAccounts.json
      DOTNET_KeyValueStoreSettings__Stores__expenseAccounts__DefaultValueValue: "{\"attributes\":{},\"add_tags\":[]}"
      FireFlyIIISettings__BaseUrl: http://firefly_iii:8080/
      FireFlyIIISettings__Token: '{{ COM_GABBRO_FIREFLY_III__ACCESS_TOKEN }}'
      NodeRedSettings__BaseUrl: http://firefly_iii_pp_node_red:1880/
    volumes:
      - /mnt/celery/gabbro/firefly_iii/pp/thunder/:/thunder
      - /mnt/celery/gabbro/firefly_iii/pp/kvs/:/keyValueStore

networks:
  firefly_iii:
volumes:
  firefly-iii-node-red-data:

