services:
  firefly_iii:
    networks:
      - nginx
      - firefly_iii
    image: fireflyiii/core:latest
    volumes:
      - /mnt/celery/gabbro/firefly_iii/upload/:/var/www/html/storage/upload
    env_file:
      - ./firefly_iii/firefly_iii.env
    environment:
      VIRTUAL_HOST: firefly-iii.gabbro
      VIRTUAL_PORT: 8080
      SITE_OWNER: burghardtnoah@gmail.com
    depends_on:
      - firefly_iii_db
  firefly_iii_db:
    networks:
      - firefly_iii
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ COM_GABBRO_FIREFLY_III__DB__USERNAME }}"
      MYSQL_PASSWORD: "{{ COM_GABBRO_FIREFLY_III__DB__PASSWORD }}"
      MYSQL_DATABASE: firefly
    volumes:
      - /mnt/celery/gabbro/firefly_iii/db/:/var/lib/mysql
  firefly_iii_importer:
    networks:
      - firefly_iii
      - nginx
    image: fireflyiii/data-importer:latest
    depends_on:
      - firefly_iii
    environment:
      VIRTUAL_HOST: firefly-iii-di.gabbro
      VIRTUAL_PORT: 8080
      FIREFLY_III_URL: 'http://firefly_iii:8080'
      FIREFLY_III_ACCESS_TOKEN: '{{ COM_GABBRO_FIREFLY_III__ACCESS_TOKEN }}'
  firefly_iii_pp_node_red:
    networks:
      - firefly_iii
      - nginx
    image: nodered/node-red:latest
    environment:
      VIRTUAL_HOST: firefly-iii-nr.gabbro
      VIRTUAL_PORT: 1880
    volumes:
      - /mnt/celery/gabbro/firefly_iii/node-red/data/:/data
      - /mnt/celery/gabbro/firefly_iii/node-red/external/:/external
  firefly_iii_pp:
    networks:
      - firefly_iii
      - nginx
    image: haumea/fireflyiii-pp:latest
    environment:
      VIRTUAL_HOST: firefly-iii-pp.gabbro
      VIRTUAL_PORT: 80
      DOTNET_KeyValueStoreSettings__Stores__assetAccounts__Path: assetAccounts.json
      DOTNET_KeyValueStoreSettings__Stores__assetAccounts__DefaultValueValue: "{\"attributes\":{},\"add_tags\":[]}"
      DOTNET_KeyValueStoreSettings__Stores__expenseAccounts__Path: expenseAccounts.json
      DOTNET_KeyValueStoreSettings__Stores__expenseAccounts__DefaultValueValue: "{\"attributes\":{},\"add_tags\":[]}"
      FireFlyIIISettings__BaseUrl: http://firefly_iii:8080/
      FireFlyIIISettings__Token: '{{ COM_GABBRO_FIREFLY_III__ACCESS_TOKEN }}'
      NodeRedSettings__BaseUrl: http://firefly_iii_pp_node_red:1880/

    volumes:
      - /mnt/celery/gabbro/firefly_iii/pp/thunder/:/thunder
      - /mnt/celery/gabbro/firefly_iii/pp/kvs/:/keyValueStore

networks:
  firefly_iii:
