workflow:
  name: Deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_COMMIT_BRANCH == "main"
      when: always

stages:
  - generate
  - deploy

build-deployment:
  stage: generate
  script:
    - echo "$INFISICAL_SECRET" > "key.txt"
    - python3 ./scripts/build.py

deploy:
  stage: deploy
  script:
    - export ANSIBLE_LOOKUP_INFISICAL_KEY=$INFISICAL_SECRET
    - export ANSIBLE_CONFIG=$(pwd)/ansible/ansible.cfg
    - cd ansible
    - ansible-playbook playbooks/deploy.yml

