workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_COMMIT_BRANCH == "main"
      when: always

stages:
  - generate
  - deploy

build-deployment:
  stage: generate
  script: |
    echo "$INFISICAL_SECRET" > "key.txt"
    echo "Running build..."
    python3 ./scripts/build.py
    if [[ -e changes.txt ]] && [[ -s changes.txt ]]; then
      echo "Compressing build..."
      tar -czf tmp.tar.gz tmp
      openssl aes-256-cbc -md sha512 -salt -pbkdf2 -iter 1000000 -in tmp.tar.gz -out tmp.enc -k $GITLAB_ENCRYPTION_KEY
    else
      echo "Skipping build export"
    fi
  artifacts:
    paths:
      - tmp.enc
      - changes.txt

deploy:
  stage: deploy
  script:
    - ansible-galaxy collection list
  dependencies:
    - build-deployment


