services:
  nginx:
    networks:
      - nginx
  influxdb2:
    networks:
      - grafana
    volumes:
      - /mnt/ssd_raid/grafana__influxdb2/:/var/lib/influxdb2
  filestash:
    networks:
      - nginx
  portainer:
    ports:
      - 9001:9001
  dashy:
    networks:
      - nginx
  radarr:
    networks:
      - nginx
    volumes:
      - /srv/storage/local/main/radarr/:/config
      - {{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/movies0
      - {{ MEDIA__DOWNLOAD_DIR }}/:/mnt/downloads
    environment:
      PGID: {{ MEDIA__GROUP }}
  radarr_4k:
    networks:
      - nginx
    volumes:
      - /srv/storage/local/main/radarr_4k/:/config
      - {{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0
      - {{ MEDIA__DOWNLOAD_DIR }}/:/mnt/downloads
    environment:
      PGID: {{ MEDIA__GROUP }}
  qbittorrent:
    volumes:
      - {{ MEDIA__DOWNLOAD_DIR}}/:/downloads
      - /srv/storage/remote/raid10/qbittorrent__incomplete/:/downloading
      - /srv/storage/local/main/qbittorrent/:/config
    networks:
      - nginx
    environment:
      PGID: {{ MEDIA__GROUP }}

networks:
  nginx:
  grafana:

# available volumes:
# /srv/storage/local/main
# /srv/storage/remote/hdd1
# /srv/storage/remote/hdd2
# /srv/storage/remote/plex4k
# /srv/storage/remote/raid10
# /srv/storage/remote/ssd_raid
