services:
  portainer:
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /etc/localtime:/etc/localtime:ro
      - more-volumes:/oh-yeah

volumes:
  more-volumes:
    - something
  another-one:
