networks:
  nginx:
  grafana:

# available volumes:
# /srv/storage/local/main
# /srv/storage/remote/hdd1
# /srv/storage/remote/hdd2
# /srv/storage/remote/plex4k
# /srv/storage/remote/raid10
# /srv/storage/remote/ssd_raid
