services:
  nginx:
    networks:
      - nginx
  influxdb2:
    networks:
      - grafana
    volumes:
      - /mnt/ssd_raid/grafana__influxdb2/:/var/lib/influxdb2
  filestash:
    networks:
      - nginx

networks:
  nginx:
  grafana:
