services:
  {{ COM_GABBRO_CONTAINER }}:
    container_name: {{ COM_GABBRO_CONTAINER }}
    labels:
      com.obsidian.host: {{ COM_GABBRO_HOST }}
      com.obsidian.service: {{ COM_GABBRO_CONTAINER }}
    environment:
      PGID: {{ COM_GABBRO_PGID }}
      PUID: {{ COM_GABBRO_PUID }}
    volumes:
      - /etc/localtime:/etc/localtime:ro