services:
  nginx:
    networks:
      - nginx
  influxdb2:
    networks:
      - grafana
    volumes:
      - /mnt/ssd_raid/inner/grafana-influxdb2/:/var/lib/influxdb2

networks:
  nginx:
  grafana:
