services:
  emby:
    image: lscr.io/linuxserver/emby:latest@sha256:7e6eff1550f3ca54aea32fdd8919226f03f2282b66d9025b88fbe5d8a320e9ee
    x-tl: +!
    networks:
      - deployments-gabbro_rathole
    environment:
      RATHOLE_VIRTUAL_PORT: 8096
      RATHOLE_VIRTUAL_HOST: "emby.haondt.dev"
      RATHOLE_INCLUDE:
    volumes:
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0:ro"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0:ro"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0:ro"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1:ro"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies:/mnt/movies1:ro"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies_hd:/mnt/hd_movies1:ro"
      - /mnt/tomato/gabbro/emby/transcode:/transcode
