services:
  emby:
    image: lscr.io/linuxserver/emby:latest@sha256:a4eb2e336e1cd9498d140dd5747f32ae8a645c14dbb4e991ab044a9a6d92a3da
    x-tl: +!
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2gb 
    networks:
      - deployments-gabbro_rathole
    environment:
      RATHOLE_VIRTUAL_PORT: 8096
      RATHOLE_VIRTUAL_HOST: "emby.haondt.dev"
      RATHOLE_INCLUDE:
    volumes:
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0:ro"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0:ro"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0:ro"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1:ro"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies:/mnt/movies1:ro"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies_hd:/mnt/hd_movies1:ro"
      - /mnt/tomato/gabbro/emby/transcode:/transcode
