services:
  influxdb2:
    networks:
      - grafana
      - nginx
    image: influxdb:2.7.5-alpine
    volumes:
      - /src/storage/remote/ssd_raid/grafana__influxdb2/:/var/lib/influxdb2
      - ./grafana/influxdb2/influxdb.conf:/etc/influxdb2/influxdb.conf
      - ./grafana/influxdb2/influx_init.sh:/docker-entrypoint-initdb.d/influx_init.sh
    environment:
      VIRTUAL_HOST: influxdb2.gabbro
      VIRTUAL_PORT: 8086
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: "{{ COM_GABBRO_GRAFANA_INFLUXDB2_INFLUXDB_INIT_USERNAME }}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "{{ COM_GABBRO_GRAFANA_INFLUXDB2_INFLUXDB_INIT_PASSWORD }}"
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry
  grafana:
    networks:
      - grafana
      - nginx
    image: grafana/grafana:latest
    user: "{{ COM_GABBRO_PUID }}:{{ MONITORING__GROUP }}"
    volumes:
      - /srv/storage/local/main/grafana/provisioning/:/etc/grafana/provisioning
      - /srv/storage/local/main/grafana/storage/:/var/lib/grafana
      - ./grafana/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb2
    environment:
      VIRTUAL_HOST: grafana.gabbro
      VIRTUAL_PORT: 3000
      GF_SECURITY_ADMIN_USER: "{{ COM_GABBRO_GRAFANA_INIT_USERNAME }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ COM_GABBRO_GRAFANA_INIT_PASSWORD }}"
