services:
  influxdb2:
    networks:
      - grafana
      - nginx
    image: docker.io/library/influxdb:2-alpine@sha256:a7a9e96c9bfc443a79d13e2b1989dc43608eb5b6c06fec6d30651ca5f8219330
    x-tl: ^!
    volumes:
      - /mnt/celery/gabbro/grafana/influxdb2/:/var/lib/influxdb2
      - ./grafana/influxdb2/influxdb.conf:/etc/influxdb2/influxdb.conf
      - ./grafana/influxdb2/influx_init.sh:/docker-entrypoint-initdb.d/influx_init.sh
    environment:
      VIRTUAL_PORT: 8086
      VIRTUAL_HOST: "influxdb2.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: "{{ COM_GABBRO_GRAFANA_INFLUXDB2_INFLUXDB_INIT_USERNAME }}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "{{ COM_GABBRO_GRAFANA_INFLUXDB2_INFLUXDB_INIT_PASSWORD }}"
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry
  grafana:
    networks:
      - grafana
      - nginx
    image: docker.io/grafana/grafana:latest@sha256:63ef3130e7cb8b85317e0bb965e452cc001929a5032800e8f64d6699cf6089da
    x-tl: +!
    user: "{{ COM_GABBRO_PUID }}:{{ COM_GABBRO_PGID }}"
    volumes:
      - /mnt/celery/gabbro/grafana/grafana/provisioning/:/etc/grafana/provisioning
      - /mnt/celery/gabbro/grafana/grafana/storage/:/var/lib/grafana
      - ./grafana/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb2
    environment:
      VIRTUAL_PORT: 3000
      GF_SECURITY_ADMIN_USER: "{{ COM_GABBRO_GRAFANA_INIT_USERNAME }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ COM_GABBRO_GRAFANA_INIT_PASSWORD }}"
      VIRTUAL_HOST: "grafana.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp

networks:
  grafana:

