services:
  plex:
    image: lscr.io/linuxserver/plex:latest@sha256:7794c25926494a63da421fabf2898dd38c4d6190f9146450fc0e29da8025ed2c
    x-tl: +!
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 4gb 
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    networks:
      - nginx
      - plex
    environment:
      VIRTUAL_PORT: 32400
      VIRTUAL_HOST: "plex.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    healthcheck:
      test: curl --fail http://localhost:32400/identity || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    volumes:
      - /mnt/celery/gabbro/plex/config:/config
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies:/mnt/movies1"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies_hd:/mnt/hd_movies1"
      - /mnt/tomato/gabbro/plex/transcode:/transcode # must be configured in settings > transcoder

networks:
  plex:
