services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
        #networks:
        #- nginx
    environment:
      PGID: {{ MEDIA__GROUP }}
      VIRTUAL_HOST: plex.gabbro
      VIRTUAL_PORT: 32400
      PLEX_CLAIM: claim-W3xr2ssxJ3WwM6AWZCHX
    volumes:
      - /srv/storage/local/main/plex/:/config
      - {{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0
      - {{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0
