services:
  tautulli:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/tautulli:latest@sha256:f289fe8c8d801471cd5f8f7a5a5edf8d2a7e70893238ade7a679d5340e641f2f
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/tautulli/:/config
    environment:
      VIRTUAL_PORT: 8181
      VIRTUAL_HOST: "tautulli.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp

