services:
  tautulli:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/tautulli:latest@sha256:73540c967731d36692cea9b8e8881c45e2734f47d5eac1ed6e5e1821f4801737
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/tautulli/:/config
    environment:
      VIRTUAL_PORT: 8181
      VIRTUAL_HOST: "tautulli.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp

