services:
  tautulli:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/tautulli:latest@sha256:b8eb3f6ef39654eb64bd27810cafaa01e723fabb4fa77bc719564b77fbbb02b1
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/tautulli/:/config
    environment:
      VIRTUAL_PORT: 8181
      VIRTUAL_HOST: "tautulli.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp

