services:
  tautulli:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/tautulli:latest@sha256:8b550f3f2615318546efedd6e850f1549551be9d4cb540e4c3ac664200c03bf7
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/tautulli/:/config
    environment:
      VIRTUAL_PORT: 8181
      VIRTUAL_HOST: "tautulli.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp

