services:
  ersatztv:
    image: jasongdove/ersatztv:latest
    networks:
      - nginx
    volumes:
      - ersatztv-data:/root/.local/share/ersatztv
      - ersatztv-transcode:/root/.local/share/etv-transcode
      # - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0"
      # - "{{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0"
      # - "{{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0"
      # - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1"
      # - "{{ MEDIA__PLEX_DIR_1 }}/movies:/mnt/movies1"
      # - "{{ MEDIA__PLEX_DIR_2 }}/tv_shows:/mnt/tv_shows2"
      # - "{{ MEDIA__PLEX_DIR_2 }}/movies:/mnt/movies2"
    environment:
      PGID: "{{ MEDIA__GROUP }}"
      VIRTUAL_HOST: ersatztv.gabbro
      VIRTUAL_PORT: 8409

volumes:
  ersatztv-data:
  ersatztv-transcode:
    driver_opts:
      type: tmpfs
      o: size=1000000
      device: tmpfs
