services:
  elysium:
    networks:
      - nginx
      - elysium
    image: registry.gitlab.com/haondt/cicd/registry/elysium:queue-e0412475
    x-tl: x
    depends_on:
      - elysium-silo
    environment:
      VIRTUAL_HOST: "elysium.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HostingSettings__Host: elysium.{{ LETSENCRYPT_HOST }}
    env_file:
      - ./elysium/elysium.env
      - ./elysium/shared.env
  elysium-silo:
    networks:
      - nginx
      - elysium
    image: registry.gitlab.com/haondt/cicd/registry/elysium-silo:queue-e0412475
    x-tl: x
    depends_on:
      - elysium-postgres
      - elysium-redis
    environment:
      VIRTUAL_HOST: "elysium-silo.{{ COM_GABBRO_HOST }}"
      VIRTUAL_PORT: 8080
      HostingSettings__Host: elysium.{{ LETSENCRYPT_HOST }}
    env_file:
      - ./elysium/shared.env
    # deploy:
    #   replicas: 2
  elysium-postgres:
    networks:
      - elysium
    image: docker.io/library/postgres:16-alpine@sha256:1c6d2f6e4d30d49c529e09a627e8178db5011dde88d955eb08db2e135e64aa09
    x-tl: ^!
    environment:
      POSTGRES_USER: elysium
      POSTGRES_PASSWORD: elysium
      PGDATA: /data/pgdata
    volumes:
      - elysium-postgres-data:/data
      - ./elysium/postgresql-init.sql:/docker-entrypoint-initdb.d/postgresql-init.sql
  elysium-redis:
    image: docker.io/library/redis:latest@sha256:acb90ced0bd769b7c04cb4c32c4494ba7b3e0ee068bdbfff0eeb0d31c2a21078
    x-tl: +!
    networks:
      - elysium

networks:
  elysium:

volumes:
  elysium-postgres-data:
