services:
  elysium:
    networks:
      - nginx
      - elysium
    image: registry.gitlab.com/haondt/cicd/registry/elysium:queue-e0412475
    x-tl: x
    depends_on:
      - elysium-silo
    environment:
      VIRTUAL_HOST: "elysium.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HostingSettings__Host: elysium.{{ LETSENCRYPT_HOST }}
    env_file:
      - ./elysium/elysium.env
      - ./elysium/shared.env
  elysium-silo:
    networks:
      - nginx
      - elysium
    image: registry.gitlab.com/haondt/cicd/registry/elysium-silo:queue-e0412475
    x-tl: x
    depends_on:
      - elysium-postgres
      - elysium-redis
    environment:
      VIRTUAL_HOST: "elysium-silo.{{ COM_GABBRO_HOST }}"
      VIRTUAL_PORT: 8080
      HostingSettings__Host: elysium.{{ LETSENCRYPT_HOST }}
    env_file:
      - ./elysium/shared.env
    # deploy:
    #   replicas: 2
  elysium-postgres:
    networks:
      - elysium
    image: docker.io/library/postgres:16-alpine@sha256:ef2235fd13b6cb29728a98ee17862ff5c9b7d20515a9b34804da4a45062695f6
    x-tl: ^!
    environment:
      POSTGRES_USER: elysium
      POSTGRES_PASSWORD: elysium
      PGDATA: /data/pgdata
    volumes:
      - elysium-postgres-data:/data
      - ./elysium/postgresql-init.sql:/docker-entrypoint-initdb.d/postgresql-init.sql
  elysium-redis:
    image: docker.io/library/redis:latest@sha256:dac8ab0340cef636bf80c4d771e338733c694885567aaabd15fe1368d6bf7c13
    x-tl: +!
    networks:
      - elysium

networks:
  elysium:

volumes:
  elysium-postgres-data:
