services:
  elysium:
    networks:
      - nginx
      - elysium
    image: registry.gitlab.com/haondt/cicd/registry/elysium:queue-e0412475
    x-tl: x
    depends_on:
      - elysium-silo
    environment:
      VIRTUAL_HOST: "elysium.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HostingSettings__Host: elysium.{{ LETSENCRYPT_HOST }}
    env_file:
      - ./elysium/elysium.env
      - ./elysium/shared.env
  elysium-silo:
    networks:
      - nginx
      - elysium
    image: registry.gitlab.com/haondt/cicd/registry/elysium-silo:queue-e0412475
    x-tl: x
    depends_on:
      - elysium-postgres
      - elysium-redis
    environment:
      VIRTUAL_HOST: "elysium-silo.{{ COM_GABBRO_HOST }}"
      VIRTUAL_PORT: 8080
      HostingSettings__Host: elysium.{{ LETSENCRYPT_HOST }}
    env_file:
      - ./elysium/shared.env
    # deploy:
    #   replicas: 2
  elysium-postgres:
    networks:
      - elysium
    image: docker.io/library/postgres:16-alpine
    x-tl: ^!
    environment:
      POSTGRES_USER: elysium
      POSTGRES_PASSWORD: elysium
      PGDATA: /data/pgdata
    volumes:
      - elysium-postgres-data:/data
      - ./elysium/postgresql-init.sql:/docker-entrypoint-initdb.d/postgresql-init.sql
  elysium-redis:
    image: docker.io/library/redis:latest@sha256:6aafb7f25fc93c4ff74e99cff8e85899f03901bc96e61ba12cd3c39e95503c73
    x-tl: +!
    networks:
      - elysium

networks:
  elysium:

volumes:
  elysium-postgres-data:
