services:
  linkding:
    image: docker.io/sissbruecker/linkding:latest@sha256:f663de3765a89c96af5381e38cfbf8a75cabbb257716653a52163000421ca45a
    x-tl: +!
    networks:
      - nginx
    volumes:
      - linkding-data:/etc/linkding/data
    env_file:
      - ./linkding/linkding.env
    environment:
      VIRTUAL_PORT: 9090
      VIRTUAL_HOST: "linkding.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
volumes:
  linkding-data:
