services:
  vaultwarden:
    image: vaultwarden/server:latest
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: vaultwarden.gabbro
      LETSENCRYPT_HOST: vaultwarden.gabbro
      VIRTUAL_PORT: 80
      HTTPS_METHOD: noredirect
    volumes:
      - /srv/storage/local/main/vaultwarden/:/data
