services:
  vaultwarden:
    image: docker.io/vaultwarden/server:1.34.3@sha256:84fd8a47f58d79a1ad824c27be0a9492750c0fa5216b35c749863093bfa3c3d7
    x-tl: "+:!!!?"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: "vaultwarden.{{ COM_GABBRO_HOST }},vaultwarden.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 80
      HTTPS_METHOD: noredirect
    volumes:
      - /mnt/celery/gabbro/vaultwarden/:/data
    ports:
      - 6969:80 # hack, for now
