services:
  vaultwarden:
    image: docker.io/vaultwarden/server:1.34.2@sha256:2981e809c332e46d49bd29e6a898ca5ba13fa431befabe52d0ce11ed237cb5ef
    x-tl: "+:!!!?"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: "vaultwarden.{{ COM_GABBRO_HOST }},vaultwarden.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 80
      HTTPS_METHOD: noredirect
    volumes:
      - /mnt/celery/gabbro/vaultwarden/:/data
    ports:
      - 6969:80 # hack, for now
