services:
  syncthing:
    networks:
      - nginx
    image: lscr.io/linuxserver/syncthing:latest@sha256:46375bb40faede6b658a4c158e9c0659dce5682eae89444d06c79cd1b009dead
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/syncthing/config/:/config
      - /mnt/celery/gabbro/syncthing/data/:/data
      - /mnt/celery/gabbro/paperless_ngx/consume/:/mnt/paperless_ngx_consume
    environment:
      VIRTUAL_HOST: "syncthing.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 8384
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
