services:
  syncthing:
    networks:
      - nginx
    image: lscr.io/linuxserver/syncthing:latest@sha256:62cd1e54568785afbdf49fdf7ea6851302edee2d9124dba40191301070c96e86
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/syncthing/config/:/config
      - /mnt/celery/gabbro/syncthing/data/:/data
      - /mnt/celery/gabbro/paperless_ngx/consume/:/mnt/paperless_ngx_consume
    environment:
      VIRTUAL_HOST: syncthing.gabbro
      VIRTUAL_PORT: 8384
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
