services:
  syncthing:
    networks:
      - nginx
    image: lscr.io/linuxserver/syncthing:latest
    volumes:
      - /srv/storage/local/main/syncthing/config/:/config
      - /srv/storage/remote/raid10/syncthing__data/:/data
      - /srv/storage/local/main/paperless_ngx/consume/:/mnt/paperless_ngx_consume
    environment:
      VIRTUAL_HOST: syncthing.gabbro
      VIRTUAL_PORT: 8384
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
