services:
  syncthing:
    networks:
      - nginx
    image: lscr.io/linuxserver/syncthing:latest@sha256:51f086a3282bd4feb9898766b925fae36249dd48fdcec395ee73cd2c29f388ae
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/syncthing/config/:/config
      - /mnt/celery/gabbro/syncthing/data/:/data
      - /mnt/celery/gabbro/paperless_ngx/consume/:/mnt/paperless_ngx_consume
    environment:
      VIRTUAL_HOST: syncthing.gabbro
      VIRTUAL_PORT: 8384
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
