services:
  syncthing:
    networks:
      - nginx
    image: lscr.io/linuxserver/syncthing:latest@sha256:210b3d07daaa68c5c496ddb2848ea0e8677c840b6acd234099d54e67cf0733c4
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/syncthing/config/:/config
      - /mnt/celery/gabbro/syncthing/data/:/data
      - /mnt/celery/gabbro/paperless_ngx/consume/:/mnt/paperless_ngx_consume
    environment:
      VIRTUAL_HOST: "syncthing.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 8384
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
