services:
  kometa_bootstrap:
    build:
      context: ./kometa
      dockerfile: bootstrap.dockerfile
    entrypoint: ['python3', '-u', '/app/bootstrap.py']
    user: "{{ COM_GABBRO_PUID }}:{{ COM_GABBRO_PGID }}"
    volumes:
      - ./kometa/bootstrap.py:/app/bootstrap.py
      - ./kometa/config.yml:/config.yml
      - /mnt/celery/gabbro/kometa/:/config
  kometa:
    image: kometateam/kometa:v2.0.2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 0.5gb 
    command: ['--run']
    networks:
      - plex
    user: "{{ COM_GABBRO_PUID }}:{{ COM_GABBRO_PGID }}"
    environment:
      VIRTUAL_HOST: .gabbro
      VIRTUAL_PORT: 8096
    volumes:
      - /mnt/celery/gabbro/kometa/:/config
      - ./kometa/TVShows.yml:/config/TVShows.yml:ro
      - ./kometa/Movies.yml:/config/Movies.yml:ro
      - ./kometa/All.yml:/config/All.yml:ro
    depends_on:
      kometa_bootstrap:
        condition: service_completed_successfully
