services:
  kometa_bootstrap:
    labels:
      dev.haondt.lifecycle: ephemeral
    build:
      context: ./kometa
      dockerfile: bootstrap.dockerfile
    x-tl: x
    entrypoint: ['python3', '-u', '/app/bootstrap.py']
    user: "{{ COM_GABBRO_PUID }}:{{ COM_GABBRO_PGID }}"
    volumes:
      - ./kometa/bootstrap.py:/app/bootstrap.py
      - ./kometa/config.yml:/config.yml
      - /mnt/celery/gabbro/kometa/:/config
  kometa:
    image: docker.io/kometateam/kometa:v2.1.0@sha256:af441b1eeaa3be6a55820f16102d950d12fa52f3bb791b835a6a768385cd3a30
    x-tl: +:.!!?
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 0.5gb 
    command: ['--run']
    networks:
      - plex
    user: "{{ COM_GABBRO_PUID }}:{{ COM_GABBRO_PGID }}"
    environment:
      VIRTUAL_HOST: .gabbro
      VIRTUAL_PORT: 8096
    volumes:
      - /mnt/celery/gabbro/kometa/:/config
      - ./kometa/TVShows.yml:/config/TVShows.yml:ro
      - ./kometa/Movies.yml:/config/Movies.yml:ro
      - ./kometa/All.yml:/config/All.yml:ro
    depends_on:
      kometa_bootstrap:
        condition: service_completed_successfully
