services:
  pyreminder:
    image: docker.io/haumea/pyreminder:latest@sha256:960b57a4db75fae98e1e075d680614bde3486c3d9648dc075ae31c56807738dc
    x-tl: +!
    labels:
      test: foo
    group_add:
      - "{{ COM_GABBRO_PGID }}"
    volumes:
      - ./pyreminder/pyreminder.yml:/config/pyreminder.yml
      - pyreminder-data:/data
volumes:
  pyreminder-data:
