services:
  pyreminder:
    image: haumea/pyreminder:latest
    x-tl: +!
    labels:
      test: foo
    group_add:
      - "{{ COM_GABBRO_PGID }}"
    volumes:
      - ./pyreminder/pyreminder.yml:/config/pyreminder.yml
      - pyreminder-data:/data
volumes:
  pyreminder-data:
