gcp_buckets:
  gabbro:
    bucket: "{{ GCP_BUCKET }}"

jobs:
  gabbro-secret-manager:
    source:
      type: http
      url: http://gsm.gabbro-ce/api/secrets
      method: get
      ext: json
      auth:
        bearer: "{{ GSM_API_KEY }}"
      encrypt: "{{ ENCRYPTION_KEY }}"
    destination:
      type: gcp_bucket
      name: gabbro_secret_manager
      config: gabbro
    schedule:
      cron: "0 0 * * *"
  syncthing:
    source:
      type: local
      path: /backup/syncthing
    destination:
      type: gcp_bucket
      name: syncthing
      config: gabbro
    schedule:
      cron: "0 0 * * *"
  vaultwarden:
    source:
      type: sqlite
      db_path: /backup/vaultwarden/db.sqlite3
    destination:
      type: gcp_bucket
      name: vaultwarden
      config: gabbro
    schedule:
      after: 0s
      cron: "0 0 * * *"


