services:
  charon:
    image: registry.gitlab.com/haondt/cicd/registry/charon:1.2.0
    x-tl: x
    volumes:
      - ./charon/credentials.json:/config/credentials.json
      - ./charon/charon.yml:/config/charon.yml
      - /mnt/celery/gabbro/syncthing/data/:/backup/syncthing/
      - /mnt/celery/gabbro/vaultwarden/db.sqlite3:/backup/vaultwarden/db.sqlite3
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /config/credentials.json
