services:
  charon:
    image: registry.gitlab.com/haondt/cicd/registry/charon:1.1.0
    volumes:
      - ./charon/credentials.json:/config/credentials.json
      - ./charon/charon.yml:/config/charon.yml
      - /srv/storage/remote/raid10/syncthing__data/:/backup/syncthing/
      - /srv/storage/local/main/vaultwarden/db.sqlite3:/backup/vaultwarden/db.sqlite3
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /config/credentials.json
