services:
  charon:
    image: registry.gitlab.com/haondt/cicd/registry/charon:latest
    volumes:
      - ./charon/credentials.json:/config/credentials.json
      - ./charon/charon.yml:/config/charon.yml
      - /srv/storage/remote/raid10/syncthing__data/:/backup/syncthing/
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /config/credentials.json
