services:
  backup:
    build:
      context: ./backup
    volumes:
      - ./backup/credentials.json:/config/credentials.json
      - /srv/storage/remote/raid10/syncthing__data/:/backup/syncthing/
    environment:
      GCP_CREDENTIALS: "/config/credentials.json"
      GCP_BUCKET: "{{ GCP_BUCKET }}"

      BACKUP__0__CRON: "* * * * *"
      BACKUP__0__NAME: "syncthing"
      BACKUP__0__LOCAL_PATH: "/backup/syncthing/"
