services:
  nginx:
    networks:
      - nginx
    image: nginxproxy/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./nginx/star_arr.conf:/etc/nginx/vhost.d/radarr.gabbro
    ports:
      - 80:80
