services:
  nginx:
    networks:
      - nginx
    image: docker.io/nginxproxy/nginx-proxy:latest@sha256:42951081b024cd9601aa5c14b4e2b3645f7782f090d5bc5e7dc7f49dcf66b323
    x-tl: "+!"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./nginx/star_arr.conf:/etc/nginx/vhost.d/radarr.{{ COM_GABBRO_HOST }}
      - ./nginx/star_arr.conf:/etc/nginx/vhost.d/sonarr.{{ COM_GABBRO_HOST }}
      - ./nginx/star_arr.conf:/etc/nginx/vhost.d/radarr-4k.{{ COM_GABBRO_HOST }}
      - ./nginx/vaultwarden.conf:/etc/nginx/vhost.d/vaultwarden.{{ COM_GABBRO_HOST }}
      - ./nginx/vaultwarden.conf:/etc/nginx/vhost.d/vaultwarden.{{ LETSENCRYPT_HOST }}
      - ./nginx/hestia.conf:/etc/nginx/vhost.d/hestia.{{ LETSENCRYPT_HOST }}
      - ./nginx/elysium.location.conf:/etc/nginx/vhost.d/elysium.{{ LETSENCRYPT_HOST }}_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
      - ./nginx/elysium-silo.location.conf:/etc/nginx/vhost.d/elysium-silo.{{ COM_GABBRO_HOST }}_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
      - ./nginx/fidi.conf:/etc/nginx/vhost.d/firefly-iii-di.gabbro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443

  nginx-acme:
    image: docker.io/nginxproxy/acme-companion:latest@sha256:180eb2b730f0acb530b7d053857805659e65665c8f0d2d6bdf107c866a0fccdd
    x-tl: +!
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-acmesh:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: "{{ DEFAULT_EMAIL }}"
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_cf
        CF_Token: {{ CF_TOKEN }}
        CF_Zone_ID: {{ CF_ZONE_ID }}
        CF_Account_ID: {{ CF_ACCOUNT_ID }}

networks:
  nginx:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acmesh:

