services:
  nginx:
    networks:
      - nginx
    image: docker.io/nginxproxy/nginx-proxy:latest@sha256:4b8578ad4af8d7b8a1e7340d1a002efcfd76251c5c7350dd034caebef54e3a04
    x-tl: "+!"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./nginx/star_arr.conf:/etc/nginx/vhost.d/radarr.{{ COM_GABBRO_HOST }}
      - ./nginx/star_arr.conf:/etc/nginx/vhost.d/sonarr.{{ COM_GABBRO_HOST }}
      - ./nginx/star_arr.conf:/etc/nginx/vhost.d/radarr-4k.{{ COM_GABBRO_HOST }}
      - ./nginx/vaultwarden.conf:/etc/nginx/vhost.d/vaultwarden.{{ COM_GABBRO_HOST }}
      - ./nginx/vaultwarden.conf:/etc/nginx/vhost.d/vaultwarden.{{ LETSENCRYPT_HOST }}
      - ./nginx/elysium.location.conf:/etc/nginx/vhost.d/elysium.{{ LETSENCRYPT_HOST }}_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
      - ./nginx/elysium-silo.location.conf:/etc/nginx/vhost.d/elysium-silo.{{ COM_GABBRO_HOST }}_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
      - ./nginx/fidi.conf:/etc/nginx/vhost.d/firefly-iii-di.gabbro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443

  nginx-acme:
    image: docker.io/nginxproxy/acme-companion:latest@sha256:d6ab6211a82edf9406a2d8194ad3c581ab46b313fcf5a49801002b95cc562cbc
    x-tl: +!
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-acmesh:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: "{{ DEFAULT_EMAIL }}"
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_cf
        CF_Token: {{ CF_TOKEN }}
        CF_Zone_ID: {{ CF_ZONE_ID }}
        CF_Account_ID: {{ CF_ACCOUNT_ID }}

networks:
  nginx:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acmesh:
