services:
  portainer:
    ports:
      - 9001:9001
    image: docker.io/portainer/agent:2.29.0@sha256:aa7939adaf63bf56145bf81c41b1a62cb4ebd598bdf8ef00c0d480313bfe3e05
    x-tl: ^:.!!?
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
