services:
  portainer:
    ports:
      - 9001:9001
    image: docker.io/portainer/agent:2.30.1@sha256:419923ea9853fb3eaf3f8562935353641bd0b556f0c97da3ccbb87da329560be
    x-tl: ^:.!!?
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
