services:
  portainer:
    ports:
      - 9001:9001
    image: docker.io/portainer/agent:2.27.1@sha256:d2e6833bb6f067962f79be262066cc96921159bc9a49a3100cacecb542522fd5
    x-tl: ^:.!!?
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
