services:
  portainer:
    ports:
      - 9001:9001
    image: docker.io/portainer/agent:2.29.1@sha256:59a5ee21805dcbb6e0712e6d93469679cf1b93769aee84e833661a07cdad590a
    x-tl: ^:.!!?
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
