services:
  portainer:
    ports:
      - 9001:9001
    image: docker.io/portainer/agent:2.29.2@sha256:3d880f293f8ce0266dabe844f30ae44cbecb7599c5030f20f39844d6d15ffe0f
    x-tl: ^:.!!?
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
