services:
  portainer:
    ports:
      - 9001:9001
    image: docker.io/portainer/agent:2.28.0@sha256:171a7389a8443501eec9902895cccd1e67e4e22ad57d120c4907f1dfba3208e7
    x-tl: ^:.!!?
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
