- name: Deploy
  hosts: gabbro
  become_user: docker
  tasks:
    - name: Copy tmp to remote
      copy:
        src: "{{ playbook_dir }}/../../tmp/"
        dest: /home/docker/gabbro/
        force: true