- name: Load changed containers list
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Load changes.txt
      slurp:
        src: "{{ playbook_dir }}/../../changes.txt"
      register: changed_containers_list
    - name: Split changes into a list
      set_fact:
        container_names_list: "{{ (changed_containers_list['content'] | b64decode).splitlines() }}"

- name: Deploy
  hosts: gabbro
  become_user: gabbro
  tasks:
    - name: Copy tmp to remote
      synchronize:
        src: "{{ playbook_dir }}/../../tmp/"
        dest: /srv/deploy/
        delete: true
      become: false
    - name: Log changed containers
      debug:
        msg: "Changed containers: {{ hostvars['localhost']['container_names_list'] }}"
    - name: Restart containers
      become: true
      become_user: gabbro
      docker_compose:
        project_src: "/srv/deploy"
        recreate: always
        remove_orphans: true
        services: "{{ hostvars['localhost']['container_names_list'] }}"
        state: present
