services:
  jobs:
    networks:
      - jobs
      - nginx
    build:
      context: jobs
    x-tl: x
    volumes:
      - ./jobs/settings.js:/data/settings.js
      - /mnt/celery/gabbro/jobs/nodered_data/:/data
    environment:
      VIRTUAL_PORT: 1880
      VIRTUAL_HOST: "jobs.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
      GSM_API_KEY: "{{ GSM_API_KEY }}"
      GCP_HEALTHCHECK_URL: "{{ GCP_HEALTHCHECK_URL }}"
      TWITCH_CLIENT_ID: "{{ TWITCH_CLIENT_ID }}"
      TWITCH_CLIENT_SECRET: "{{ TWITCH_CLIENT_SECRET }}"
      TWITCH_CODE: "{{ TWITCH_CODE }}"
      TWITCH_REDIRECT_URL: "http://localhost"
      TWITCH_USER_ID: "{{ TWITCH_USER_ID }}" 

  jobs-redis: 
    image: redis
    x-tl: +!
    networks:
      - jobs
  jobs-redis-insight:
    image: redis/redisinsight
    x-tl: +!
    networks:
      - jobs
      - nginx
    environment:
      VIRTUAL_PORT: 5540
      VIRTUAL_HOST: "jobs-redis.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    volumes:
      - jobs-redis-insight-data:/data

networks:
  jobs:
volumes:
  jobs-redis-insight-data:
