services:
  jobs:
    networks:
      - jobs
      - nginx
    build:
      context: jobs
    volumes:
      - ./jobs/settings.js:/data/settings.js
      - /mnt/celery/gabbro/jobs/nodered_data/:/data
    environment:
      VIRTUAL_PORT: 1880
      VIRTUAL_HOST: "jobs.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      GSM_API_KEY: "{{ GSM_API_KEY }}"
  jobs-redis: 
    image: redis
    networks:
      - jobs
  jobs-redis-insight:
    image: redis/redisinsight
    networks:
      - jobs
      - nginx
    environment:
      VIRTUAL_PORT: 5540
      VIRTUAL_HOST: "jobs-redis.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
    volumes:
      - jobs-redis-insight-data:/data

networks:
  jobs:
volumes:
  jobs-redis-insight-data:
