services:
  helios:
    networks:
      - nginx
    image: haumea/helios
    x-tl: x
    environment:
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: "helios.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    volumes:
      - ./helios/helios.yml:/config/helios.yml
      - /mnt/celery/gabbro/helios:/data
