services:
  midas:
    networks:
      - nginx
      - midas
    image: registry.gitlab.com/haondt/cicd/registry/midas:0.1.11
    group_add:
      - "{{ COM_GABBRO_PGID }}"
    volumes:
      - /mnt/celery/gabbro/midas/midas__data/:/data
    depends_on:
      - midas-data-init
      - midas-node-red
    environment:
      VIRTUAL_HOST: "midas.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      NodeRedSettings__ClientUrl: "https://midas-node-red.{{ LETSENCRYPT_HOST }}"
    env_file:
      - ./midas/midas.env

  midas-node-red:
    networks:
      - nginx
      - midas
    build:
      context: midas/nodered
    volumes:
      - ./midas/nodered/settings.js:/data/settings.js
      - /mnt/celery/gabbro/midas/nodered__data/:/data
    environment:
      VIRTUAL_HOST: "midas-node-red.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 1880
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      MIDAS_API_URL: http://midas:8080/

  midas-data-init:
    group_add:
      - "{{ COM_GABBRO_PGID }}"
    volumes:
      - /mnt/celery/gabbro/midas/midas__data/:/data
    user: root
    image: alpine
    command: >
      sh -c "
        if [ ! -f /data/.initialized ]; then
          chgrp -R {{ COM_GABBRO_PGID }} /data && chmod -R 775 /data && touch /data/.initialized;
        fi"

networks:
  midas:
