services:
  monica:
    networks:
      - nginx
      - monica
    image: lscr.io/linuxserver/monica:latest@sha256:0b1983320b9d596304de2daf026fd499558d08f6d8b474d23d5274f02d0b15ed
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/monica/monica/:/config
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: "monica.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
      DB_HOST: monica_db
      DB_USERNAME: "{{ COM_GABBRO_MONICA__DB__USERNAME }}"
      DB_PASSWORD: "{{ COM_GABBRO_MONICA__DB__PASSWORD }}"
      DB_PORT: 3306
      DB_DATABASE: monica
      APP_URL: https://monica.{{ LETSENCRYPT_HOST }}
      APP_ENV: production
    depends_on:
      - monica_db

  monica_db:
    networks:
      - monica
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ COM_GABBRO_MONICA__DB__USERNAME }}"
      MYSQL_PASSWORD: "{{ COM_GABBRO_MONICA__DB__PASSWORD }}"
      MYSQL_DATABASE: monica
    volumes:
      - /mnt/celery/gabbro/monica/mariadb/:/var/lib/mysql

networks:
  monica:

