services:
  monica:
    networks:
      - nginx
      - monica
    image: lscr.io/linuxserver/monica:latest
    volumes:
      - /srv/storage/local/main/monica/monica/:/config
    environment:
      VIRTUAL_HOST: monica.gabbro
      VIRTUAL_PORT: 80
      DB_HOST: monica_db
      DB_USERNAME: {{ COM_GABBRO_MONICA__DB__USERNAME }}
      DB_PASSWORD: {{ COM_GABBRO_MONICA__DB__PASSWORD }}
      APP_URL: http://monica.gabbro/
    depends_on:
      - monica_db

  monica_db:
    networks:
      - monica
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: {{ COM_GABBRO_MONICA__DB__USERNAME }}
      MYSQL_PASSWORD: {{ COM_GABBRO_MONICA__DB__PASSWORD }}
      MYSQL_DATABASE: monica
    volumes:
      - /srv/storage/local/main/monica/db/:/var/lib/mysql

networks:
  monica:

