services:
  monica:
    networks:
      - nginx
      - monica
    image: lscr.io/linuxserver/monica:latest
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/monica/monica/:/config
    environment:
      VIRTUAL_HOST: monica.gabbro
      VIRTUAL_PORT: 80
      DB_HOST: monica_db
      DB_USERNAME: "{{ COM_GABBRO_MONICA__DB__USERNAME }}"
      DB_PASSWORD: "{{ COM_GABBRO_MONICA__DB__PASSWORD }}"
      DB_PORT: 3306
      DB_DATABASE: monica
      APP_URL: http://monica.gabbro/
    depends_on:
      - monica_db

  monica_db:
    networks:
      - monica
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ COM_GABBRO_MONICA__DB__USERNAME }}"
      MYSQL_PASSWORD: "{{ COM_GABBRO_MONICA__DB__PASSWORD }}"
      MYSQL_DATABASE: monica
    volumes:
      - /mnt/celery/gabbro/monica/mariadb/:/var/lib/mysql

networks:
  monica:

