services:
  nextcloud:
    networks:
      - nginx
      - nextcloud
    image: docker.io/library/nextcloud:latest@sha256:aa2054838537642ce4198f591803d72796e4934784654774f7941ec8573eb55d
    x-tl: +!
    volumes:
      - nextcloud-data:/var/www/html
      - /mnt/celery/gabbro/nextcloud/data:/mnt/celery
    links:
      - nextcloud-db
    environment:
      VIRTUAL_HOST: nextcloud.gabbro
      VIRTUAL_PORT: 80
      MYSQL_USER: nextcloud
      MYSQL_HOST: nextcloud-db
      MYSQL_PASSWORD: "{{ COM_GABBRO_NEXTCLOUD_DB_PASSWORD }}"
      MYSQL_DATABASE: nextcloud

  nextcloud-db:
    networks:
      - nextcloud
    image: docker.io/library/mariadb:11@sha256:310d29fbb58169dcddb384b0ff138edb081e2773d6e2eceb976b3668089f2f84
    x-tl: ^!
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "{{ COM_GABBRO_NEXTCLOUD_DB_PASSWORD }}"
      MYSQL_DATABASE: nextcloud

volumes:
  nextcloud-db-data:
  nextcloud-data:

networks:
  nextcloud:

