services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest@sha256:7ae36aab93ef9b6aaff02b37f8bb23df84bb2d7a3f6054ec8fc466072a648ce2
    x-tl: +!
    networks:
      - deployments-gabbro_rathole
    environment:
      JELLYFIN_PublishedServerUrl: https://jellyfin.haondt.dev
      RATHOLE_VIRTUAL_PORT: 8096
      RATHOLE_VIRTUAL_HOST: "jellyfin.haondt.dev"
      RATHOLE_INCLUDE:
    volumes:
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies:/mnt/movies1"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies_hd:/mnt/hd_movies1"
      - /mnt/tomato/gabbro/jellyfin/cache:/cache
      - /mnt/celery/gabbro/jellyfin/config/:/config
networks:
  deployments-gabbro_rathole:
    external: true

