services:
  jellyfin:
    image: jellyfin/jellyfin
    networks:
      - nginx
    environment:
      JELLYFIN_PublishedServerUrl: http://jellyfin.{{ LETSENCRYPT_HOST }}
      VIRTUAL_PORT: 8096
      VIRTUAL_HOST: "jellyfin.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache

volumes:
  jellyfin-config:
  jellyfin-cache:
