services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest@sha256:96b09723b22fdde74283274bdc1f63b9b76768afd6045dd80d4a4559fc4bb7f3
    x-tl: +!
    networks:
      - nginx
    environment:
      JELLYFIN_PublishedServerUrl: http://jellyfin.{{ LETSENCRYPT_HOST }}
      VIRTUAL_PORT: 8096
      VIRTUAL_HOST: "jellyfin.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache

volumes:
  jellyfin-config:
  jellyfin-cache:
