services:
  jellyfin:
    image: jellyfin/jellyfin
    networks:
      - nginx
    environment:
      JELLYFIN_PublishedServerUrl: http://jellyfin.gabbro
      VIRTUAL_HOST: jellyfin.gabbro
      VIRTUAL_PORT: 8096
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache

volumes:
  jellyfin-config:
  jellyfin-cache:
