services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest@sha256:7ae36aab93ef9b6aaff02b37f8bb23df84bb2d7a3f6054ec8fc466072a648ce2
    x-tl: +!
    networks:
      - nginx
    environment:
      JELLYFIN_PublishedServerUrl: http://jellyfin.{{ LETSENCRYPT_HOST }}
      VIRTUAL_PORT: 8096
      VIRTUAL_HOST: "jellyfin.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache

volumes:
  jellyfin-config:
  jellyfin-cache:
