services:
  filestash:
    networks:
      - nginx
    image: docker.io/machines/filestash:latest@sha256:e42a57cf746a030aa21155f30ce26c5a92cd48c151e23ad3a06e326e847ec5bf
    x-tl: +!
    environment:
      APPLICATION_URL: "filestash.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 8334
      VIRTUAL_HOST: "filestash.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
