services:
  filestash:
    networks:
      - nginx
    image: machines/filestash:latest
    environment:
      APPLICATION_URL: filestash.gabbro
      VIRTUAL_HOST: filestash.gabbro
      VIRTUAL_PORT: 8334
