services:
  filestash:
    networks:
      - nginx
    image: docker.io/machines/filestash:latest@sha256:9484b13c16d8ba4d2faae7486fa241c8def7c476a8c0ad8590066af20a5dfb10
    x-tl: +!
    environment:
      APPLICATION_URL: "filestash.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 8334
      VIRTUAL_HOST: "filestash.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
