services:
  filestash:
    networks:
      - nginx
    image: docker.io/machines/filestash:latest@sha256:372aa3d53c5bb3f33e7ea895ca74213091c4860da652f2993e35585cb6c7818f
    x-tl: +!
    environment:
      APPLICATION_URL: "filestash.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 8334
      VIRTUAL_HOST: "filestash.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
