services:
  paperless_ngx_broker:
    networks:
      - paperless_ngx
    image: docker.io/library/redis:7@sha256:386e6c443372b9ba651d593baa881c802f3d3f093e2586602e05d6ba47ea733e
    x-tl: ^!
    volumes:
      - /mnt/celery/gabbro/paperless_ngx/redis/:/data

  paperless_ngx_db:
    networks:
      - paperless_ngx
    image: docker.io/library/mariadb:10@sha256:34adebbac117c8ce649040e009f520fb79e577c68cc4e57debdf91befa53907f
    x-tl: ^!
    volumes:
      - /mnt/celery/gabbro/paperless_ngx/db/:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

  paperless_ngx:
    networks:
      - nginx
      - paperless_ngx
    image: ghcr.io/paperless-ngx/paperless-ngx:latest@sha256:2096725a544b81d07d35ac123aca079bcb859e03c73d03acb0105dd2629b3dea
    x-tl: +!
    depends_on:
      - paperless_ngx_db
      - paperless_ngx_broker
    volumes:
      - /mnt/celery/gabbro/paperless_ngx/data/:/usr/src/paperless/data
      - /mnt/celery/gabbro/paperless_ngx/media/:/usr/src/paperless/media
      - /mnt/celery/gabbro/paperless_ngx/export/:/usr/src/paperless/export
      - /mnt/celery/gabbro/paperless_ngx/consume/:/usr/src/paperless/consume
    environment:
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: "paperless-ngx.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp

      PAPERLESS_REDIS: redis://paperless_ngx_broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: paperless_ngx_db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_URL: https://paperless-ngx.{{ LETSENCRYPT_HOST }}
      PAPERLESS_TIME_ZONE: America/Edmonton

      PAPERLESS_ADMIN_USER: "{{ PAPERLESS_ADMIN_USER }}"
      PAPERLESS_ADMIN_PASSWORD: "{{ PAPERLESS_ADMIN_PASSWORD }}"

networks:
  paperless_ngx:

