services:
  samba:
    image: dockurr/samba:4.20.2
    x-tl: x
    environment:
      USER: "samba"
      PASS: "samba"
      UID: "{{ COM_GABBRO_PGID }}"
      GID: "{{ COM_GABBRO_PUID }}"
    ports:
      - 445:445
    volumes:
      - /mnt/celery/gabbro/samba/data:/storage
      - ./samba/smb.conf:/etc/samba/smb.conf
