services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      VIRTUAL_HOST: radarr.gabbro
      VIRTUAL_PORT: 7878
  radarr_4k:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      VIRTUAL_HOST: radarr-4k.gabbro
      VIRTUAL_PORT: 7878