services:
  radarr:
    image: docker.io/linuxserver/radarr:latest@sha256:c2adf66bafefa781401d07d358e399c476bdffb9a179a2780bb465bda8a55a51
    x-tl: +!
    networks:
      - nginx
      - plex
    volumes:
      - /mnt/celery/gabbro/radarr/:/config
      - "{{ MEDIA__DOWNLOAD_DIR }}/:/downloads"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies:/mnt/movies1"
    environment:
      VIRTUAL_PORT: 7878
      VIRTUAL_HOST: "radarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
  radarr_4k:
    image: docker.io/linuxserver/radarr:latest@sha256:c2adf66bafefa781401d07d358e399c476bdffb9a179a2780bb465bda8a55a51
    x-tl: +!
    networks:
      - nginx
      - plex
    volumes:
      - /mnt/celery/gabbro/radarr_4k/:/config
      - "{{ MEDIA__DOWNLOAD_DIR }}/:/downloads"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies_hd:/mnt/hd_movies1"
    environment:
      VIRTUAL_PORT: 7878
      VIRTUAL_HOST: "radarr-4k.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
