services:
  radarr:
    image: docker.io/linuxserver/radarr:latest@sha256:06f209efdfb25df8eaa6c275f6106d0a9e6b2c8502bd6dde3f95683c2a66aac1
    x-tl: +!
    networks:
      - nginx
      - plex
    volumes:
      - /mnt/celery/gabbro/radarr/:/config
      - "{{ MEDIA__DOWNLOAD_DIR }}/:/downloads"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies:/mnt/movies1"
    environment:
      VIRTUAL_PORT: 7878
      VIRTUAL_HOST: "radarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
  radarr_4k:
    image: docker.io/linuxserver/radarr:latest@sha256:23677e1cb09bd957796f4521748f0eff9eb65d883949c10442635eabe64b750a
    x-tl: +!
    networks:
      - nginx
      - plex
    volumes:
      - /mnt/celery/gabbro/radarr_4k/:/config
      - "{{ MEDIA__DOWNLOAD_DIR }}/:/downloads"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies_hd:/mnt/hd_movies1"
    environment:
      VIRTUAL_PORT: 7878
      VIRTUAL_HOST: "radarr-4k.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
