services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:aa566541ea012f41dd0eedc8bbc67910456713b750d1ace663950ce934269036
    x-tl: "+!"
    networks:
      - nginx
      - plex
    volumes:
      - /mnt/celery/gabbro/sonarr/:/config
      - "{{ MEDIA__DOWNLOAD_DIR }}/:/downloads"
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1"
    environment:
      VIRTUAL_PORT: 8989
      VIRTUAL_HOST: "sonarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp

