services:
  sonarr:
    networks:
      - nginx
    volumes:
      - /srv/storage/local/main/sonarr/:/config
      - {{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0
      - {{ MEDIA__DOWNLOAD_DIR }}/:/mnt/downloads
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      PGID: {{ MEDIA__GROUP }}
      VIRTUAL_HOST: sonarr.gabbro
      VIRTUAL_PORT: 8989

