services:
  sonarr:
    networks:
      - nginx
      - plex
    volumes:
      - /mnt/celery/gabbro/sonarr/:/config
      - "{{ MEDIA__DOWNLOAD_DIR }}/:/downloads"
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1"
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      VIRTUAL_HOST: sonarr.gabbro
      VIRTUAL_PORT: 8989

