services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:cefa1c97ba8f5db60c1c89d04015ead764d3b850b4fbdc5784bdde2a02d72350
    x-tl: "+!"
    networks:
      - nginx
      - plex
    volumes:
      - /mnt/celery/gabbro/sonarr/:/config
      - "{{ MEDIA__DOWNLOAD_DIR }}/:/downloads"
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1"
    environment:
      VIRTUAL_PORT: 8989
      VIRTUAL_HOST: "sonarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp

