services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:bb50bac26881613af15deb4df891e4a7cb09e3333aec20a0522cb188fb22b11d
    x-tl: "+!"
    networks:
      - nginx
      - plex
    volumes:
      - /mnt/celery/gabbro/sonarr/:/config
      - "{{ MEDIA__DOWNLOAD_DIR }}/:/downloads"
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1"
    environment:
      VIRTUAL_PORT: 8989
      VIRTUAL_HOST: "sonarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp

