services:
  prowlarr:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/prowlarr:develop@sha256:ed13ea2ebf86bc9436f1f3459166952e01e2f883dc6d488158239bbd0ba77cdd
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/prowlarr/:/config
    environment:
      VIRTUAL_PORT: 9696
      VIRTUAL_HOST: "prowlarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
