services:
  prowlarr:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/prowlarr:develop@sha256:9001b9023708dbd03df9341f313785a643724fcb74b566d01378682d8cdef8a3
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/prowlarr/:/config
    environment:
      VIRTUAL_PORT: 9696
      VIRTUAL_HOST: "prowlarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
