services:
  prowlarr:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/prowlarr:develop@sha256:1083c1769d7e9111c6227b2748bab0cb4a8514233b9f2d1d9f327eca71359312
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/prowlarr/:/config
    environment:
      VIRTUAL_PORT: 9696
      VIRTUAL_HOST: "prowlarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
