services:
  prowlarr:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/prowlarr:develop@sha256:5e779891566a522df703a96ebdf72196267e6793f47f2514add7ad4db9552283
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/prowlarr/:/config
    environment:
      VIRTUAL_PORT: 9696
      VIRTUAL_HOST: "prowlarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
