services:
  prowlarr:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/prowlarr:develop@sha256:07f8b11d89533ce9df98f3a05588c9395a529cad3a417e915f594ff944d40d14
    x-tl: +!
    volumes:
      - /mnt/celery/gabbro/prowlarr/:/config
    environment:
      VIRTUAL_PORT: 9696
      VIRTUAL_HOST: "prowlarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
