services:
  prowlarr:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/prowlarr:develop
    volumes:
      - /srv/storage/local/main/prowlarr/:/config
    environment:
      VIRTUAL_HOST: prowlarr.gabbro
      VIRTUAL_PORT: 9696
