services:
  bazarr:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/bazarr:latest@sha256:36f4ba69ab5bfb32c384ea84cf0036b8b6e07fb9a7ab65885f3619de2a8318f8
    x-tl: "+!"
    volumes:
      - /mnt/celery/gabbro/bazarr/:/config
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies:/mnt/movies1"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies_hd:/mnt/hd_movies1"
    environment:
      VIRTUAL_PORT: 6767
      VIRTUAL_HOST: "bazarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
