services:
  bazarr:
    networks:
      - nginx
      - plex
    image: lscr.io/linuxserver/bazarr:latest@sha256:b98bdcac54db7ed05524fb63447b855d7fc419428222b3827b1cc9655f95bf51
    x-tl: "+!"
    volumes:
      - /mnt/celery/gabbro/bazarr/:/config
      - "{{ MEDIA__PLEX_DIR_0 }}/tv_shows:/mnt/tv_shows0"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies:/mnt/movies0"
      - "{{ MEDIA__PLEX_DIR_0 }}/movies_hd:/mnt/hd_movies0"
      - "{{ MEDIA__PLEX_DIR_1 }}/tv_shows:/mnt/tv_shows1"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies:/mnt/movies1"
      - "{{ MEDIA__PLEX_DIR_1 }}/movies_hd:/mnt/hd_movies1"
    environment:
      VIRTUAL_PORT: 6767
      VIRTUAL_HOST: "bazarr.{{ LETSENCRYPT_HOST }}"
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
      HTTPS_METHOD: nohttp
