services:
  tandoor_db:
    image: docker.io/library/postgres:16-alpine@sha256:7c688148e5e156d0e86df7ba8ae5a05a2386aaec1e2ad8e6d11bdf10504b1fb7
    x-tl: ^!
    volumes:
      - /mnt/celery/gabbro/tandoor/postgresql:/data
    env_file:
      - ./tandoor/tandoor.env
    networks:
      - tandoor

  tandoor:
    image: docker.io/vabene1111/recipes:1.5.35@sha256:188da7487f777101c6abe996284df7966d9dd58c9b676447d5f880a5268a4393
    x-tl: +:.!!?
    env_file:
      - ./tandoor/tandoor.env
    volumes:
      - tandoor-static:/opt/recipes/staticfiles
      - /mnt/celery/gabbro/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - tandoor_db
    networks:
      - tandoor

  tandoor_nginx:
    image: docker.io/library/nginx:mainline-alpine@sha256:f741b7f2e82ec8e3daa163b089d48ec163ad0b015d859a1e4f0f2a6202e8cc22
    x-tl: +!
    env_file:
      - ./tandoor/tandoor.env
    depends_on:
      - tandoor
    volumes:
      - ./tandoor/nginx:/etc/nginx/conf.d:ro
      - tandoor-static:/static:ro
      - /mnt/celery/gabbro/tandoor/mediafiles:/media:ro
    networks:
      - tandoor
      - nginx
    environment:
      VIRTUAL_HOST: "tandoor.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"

networks:
  tandoor:

volumes:
  tandoor-static:
