services:
  tandoor_db:
    image: docker.io/library/postgres:16-alpine@sha256:1c6d2f6e4d30d49c529e09a627e8178db5011dde88d955eb08db2e135e64aa09
    x-tl: ^!
    volumes:
      - /mnt/celery/gabbro/tandoor/postgresql:/data
    env_file:
      - ./tandoor/tandoor.env
    networks:
      - tandoor

  tandoor:
    image: docker.io/vabene1111/recipes:2.2.1@sha256:fec585c765c6643344724d1255f075f12ce3c2d38ea7051f599e09f10d5b7ddd
    x-tl: +:.!!?
    env_file:
      - ./tandoor/tandoor.env
    volumes:
      - tandoor-static:/opt/recipes/staticfiles
      - /mnt/celery/gabbro/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - tandoor_db
    networks:
      - tandoor

  tandoor_nginx:
    image: docker.io/library/nginx:mainline-alpine@sha256:42a516af16b852e33b7682d5ef8acbd5d13fe08fecadc7ed98605ba5e3b26ab8
    x-tl: +!
    env_file:
      - ./tandoor/tandoor.env
    depends_on:
      - tandoor
    volumes:
      - ./tandoor/nginx:/etc/nginx/conf.d:ro
      - tandoor-static:/static:ro
      - /mnt/celery/gabbro/tandoor/mediafiles:/media:ro
    networks:
      - tandoor
      - nginx
    environment:
      VIRTUAL_HOST: "tandoor.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"

networks:
  tandoor:

volumes:
  tandoor-static:
