services:
  tandoor_db:
    image: docker.io/library/postgres:16-alpine@sha256:8ffca822c1933bdc8be7dbbe9c2330974bdb43f5027f47717772fa35925412b0
    x-tl: ^!
    volumes:
      - /mnt/celery/gabbro/tandoor/postgresql:/data
    env_file:
      - ./tandoor/tandoor.env
    networks:
      - tandoor

  tandoor:
    image: docker.io/vabene1111/recipes:2.0.2@sha256:79f337a334207d0fe49732197ee721f363aeaac8a600b75560e23c72ba5a8c25
    x-tl: +:.!!?
    env_file:
      - ./tandoor/tandoor.env
    volumes:
      - tandoor-static:/opt/recipes/staticfiles
      - /mnt/celery/gabbro/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - tandoor_db
    networks:
      - tandoor

  tandoor_nginx:
    image: docker.io/library/nginx:mainline-alpine@sha256:2459838ed006e699c252db374550c91490068bbf3b35fa8b9d29bfe0e31b8b95
    x-tl: +!
    env_file:
      - ./tandoor/tandoor.env
    depends_on:
      - tandoor
    volumes:
      - ./tandoor/nginx:/etc/nginx/conf.d:ro
      - tandoor-static:/static:ro
      - /mnt/celery/gabbro/tandoor/mediafiles:/media:ro
    networks:
      - tandoor
      - nginx
    environment:
      VIRTUAL_HOST: "tandoor.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"

networks:
  tandoor:

volumes:
  tandoor-static:
