services:
  tandoor_db:
    image: docker.io/library/postgres:16-alpine@sha256:04c92036fc82720215c235f150dde30e44ad5789af2db78f61540fe0b9ecf16c
    x-tl: ^!
    volumes:
      - /mnt/celery/gabbro/tandoor/postgresql:/data
    env_file:
      - ./tandoor/tandoor.env
    networks:
      - tandoor

  tandoor:
    image: docker.io/vabene1111/recipes:1.5.35@sha256:188da7487f777101c6abe996284df7966d9dd58c9b676447d5f880a5268a4393
    x-tl: +:.!!?
    env_file:
      - ./tandoor/tandoor.env
    volumes:
      - tandoor-static:/opt/recipes/staticfiles
      - /mnt/celery/gabbro/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - tandoor_db
    networks:
      - tandoor

  tandoor_nginx:
    image: docker.io/library/nginx:mainline-alpine@sha256:6e39bb3765ac959c7e1240509636173417a5e37abf140f418401e2fa73970bbe
    x-tl: +!
    env_file:
      - ./tandoor/tandoor.env
    depends_on:
      - tandoor
    volumes:
      - ./tandoor/nginx:/etc/nginx/conf.d:ro
      - tandoor-static:/static:ro
      - /mnt/celery/gabbro/tandoor/mediafiles:/media:ro
    networks:
      - tandoor
      - nginx
    environment:
      VIRTUAL_HOST: "tandoor.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"

networks:
  tandoor:

volumes:
  tandoor-static:
